# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
