# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170927_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='crews', to='users.Friend')),
            ],
        ),
    ]
